"""Generate all 18 functional tool pages with shared controls and live visuals."""
from pathlib import Path
from html import escape as E
import json
R=Path(__file__).resolve().parents[1]
def num(key,label,value,min=None,max=None,step='any'):return dict(key=key,label=label,value=value,min=min,max=max,step=step,type='number')
def sel(key,label,options):return dict(key=key,label=label,options=options,type='select')
def text(key,label,value=''):return dict(key=key,label=label,value=value,type='text')
def slider(key,label,value,min,max):return dict(key=key,label=label,value=value,min=min,max=max,step=1,type='range')
mode=lambda options:sel('mode','Calculation direction',options)
common=[num('lrv','Lower range value',0),num('urv','Upper range value',100),text('unit','Engineering unit','bar')]
configs={
'ma-converter':([mode([('current','Current → process value'),('reverse','Process value → current')]),*common,num('value','Loop current (mA)',12)],'PV = LRV + (mA − 4) × (URV − LRV) / 16','Change current from 4 to 12 to 20 mA. For a 0–100 range, results are 0, 50 and 100.','signal-scaling-guide'),
'dp-flow-simulator':([num('dp','Measured DP (kPa)',25,0),num('dpmax','Maximum DP (kPa)',100,0),num('qmax','Maximum flow',200,0),text('unit','Flow unit','m³/h')],'Q = Qmax × √(DP / DPmax)','At 25 kPa DP with 100 kPa maximum DP and 200 m³/h maximum flow, the flow is 100 m³/h.','dp-flow-square-root'),
'pressure-calibrator':([*common,slider('position','Test position (% of span)',50,0,100)],'Applied = LRV + span × % / 100; output = 4 + 16 × % / 100','For 0–100 bar, the midpoint is 50 bar and 12 mA. Rising and falling points help compare hysteresis.','5-point-transmitter-calibration'),
'2oo3-simulator':([sel('s'+str(i),'Sensor '+str(i),[('0','Normal'),('1','Trip demand')]) for i in range(1,4)],'Trip = (S1 AND S2) OR (S1 AND S3) OR (S2 AND S3)','Select one trip demand: no trip. Select a second demand: trip becomes active.','voting-and-cause-effect'),
'unit-converter':([sel('kind','Quantity',[('pressure','Pressure'),('temperature','Temperature')]),num('value','Input value',1),sel('from','From unit',[('bar','bar')]),sel('to','To unit',[('kPa','kPa')])],'1 bar = 100 kPa; °F = 1.8 × °C + 32; K = °C + 273.15','One bar is 100 kPa. Choose temperature and enter 100 °C to obtain 212 °F.','signal-scaling-guide'),
'rtd-pt100':([mode([('temperature','Temperature → resistance'),('resistance','Resistance → temperature')]),num('value','Temperature (°C)',100),sel('wires','Lead-wire model',[('4','4-wire: ideal compensation'),('3','3-wire: ideal matched leads'),('2','2-wire: equal lead resistances')]),num('lead','Resistance of each lead (Ω)',1,0,100)],'R = 100 × [1 + A·T + B·T² + C·(T−100)·T³]; C term only below 0 °C','A nominal Pt100 is 100 Ω at 0 °C and 138.5055 Ω at 100 °C. Two 1 Ω leads add 2 Ω in the two-wire model.','rtd-and-thermocouple'),
 'thermocouple-converter':([sel('type','Thermocouple type',[('K','K: 0…1372 °C'),('J','J: 0…760 °C'),('T','T: 0…400 °C')]),mode([('temperature','Temperature → measured mV'),('voltage','Measured mV → temperature')]),num('value','Hot junction (°C)',100),num('cj','Reference-junction temperature (°C)',0,0,100)],'Emeasured = Etype(Thot) − Etype(Treference)','Type K at 100 °C with a 0 °C reference produces approximately 4.096 mV. Raising the reference temperature reduces measured EMF.','rtd-and-thermocouple'),
 'hydrostatic-level':([mode([('height','Height → pressure'),('pressure','Pressure → height')]),num('density','Liquid density (kg/m³)',1000,0),num('height','Tank measuring height (m)',5,0),num('value','Liquid height (m)',2.5,0)],'Pressure (kPa) = density × 9.80665 × height / 1000','A 2.5 m water column at 1000 kg/m³ produces 24.5166 kPa. Change density to see why composition matters.','dp-level-wet-dry-leg'),
 'wet-leg-dry-leg':([sel('leg','LP reference leg',[('wet','Wet leg'),('dry','Dry gas leg')]),num('density','Process density (kg/m³)',800,0),num('height','Level measuring span (m)',4,0),num('offset','Transmitter below bottom tap: z (m)',1,0),num('referenceDensity','Wet-leg fill density (kg/m³)',1000,0),num('referenceHeight','Wet-leg vertical head above transmitter (m)',5,0),slider('position','Level (% of span)',50,0,100)],'DP = ρprocess × g × (h + z) − ρreference × g × Hreference','With 800 kg/m³ process, 4 m span, 1 m offset and 5 m water wet leg: LRV = −41.1879 kPa and URV = −9.8067 kPa.','dp-level-wet-dry-leg'),
 'valve-cv':([num('flow','Liquid flow (m³/h)',10,0),num('sg','Liquid specific gravity',1,0),num('drop','Valve differential pressure (bar)',1,0)],'Kv = Q(m³/h) × √(SG / ΔPbar); Cv = Kv / 0.865','At 10 m³/h of water and 1 bar drop, Kv = 10 and Cv ≈ 11.561. This is a simplified coefficient estimate.','valve-cv-basics'),
 'pid-simulator':([num('kp','Proportional gain Kp',2,0,20,.1),num('ki','Integral gain Ki (1/s)',.1,0,20,.01),num('kd','Derivative gain Kd (s)',0,0,20,.1),num('tau','Process time constant (s)',10,1,100),num('gain','Process static gain',1,.1,3,.1),slider('setpoint','Setpoint (%)',50,1,90),slider('disturbance','Disturbance at 100 s (points)',-10,-30,30)],'u = Kp·e + Ki·∫e dt − Kd·dy/dt; τ·dy/dt = processGain·u + disturbance − y','Set Ki to zero and compare the steady error with a positive Ki. Compare output saturation and recovery after the disturbance.','pid-response-basics'),
 'loop-voltage':([num('supply','Minimum supply voltage (V)',24,0),num('current','Maximum loop current (mA)',20,0),num('resistance','Total loop resistance (Ω)',250,0),num('device','Transmitter minimum voltage (V)',12,0),num('other','Other fixed voltage drops (V)',2,0)],'Margin = supply − transmitter minimum − fixed drops − I × R','24 V supply, 12 V transmitter, 2 V fixed drop and 250 Ω at 20 mA leave 5 V margin.','loop-voltage-and-cables'),
 'cable-sizing':([num('length','One-way cable route (m)',500,0),num('area','Conductor area (mm²)',1.5,0),num('current','Loop current (mA)',20,0),num('temperature','Conductor temperature (°C)',20,-20,100),sel('material','Conductor material',[('copper','Copper'),('aluminium','Aluminium')])],'Rloop = 2Lρ20[1 + α(T−20)] / A; drop = I × Rloop','500 m one-way copper, 1.5 mm², 20 °C: Rloop ≈ 11.494 Ω and drop ≈ 0.2299 V at 20 mA.','loop-voltage-and-cables'),
 'ohms-law':([sel('mode','Known quantities',[('VI','Voltage + current'),('VR','Voltage + resistance'),('IR','Current + resistance'),('VP','Voltage + power'),('IP','Current + power'),('RP','Resistance + power')]),num('a','Voltage (V)',24,0),num('b','Current (A)',.02,0)],'V = I × R; P = V × I','24 V across a load drawing 0.02 A corresponds to 1200 Ω and 0.48 W.','loop-voltage-and-cables'),
 'calibration-error':([num('lrv','Lower range value',0),num('urv','Upper range value',100),num('expected','Expected value',50),num('measured','Measured value',50.2),num('tolerance','Allowed error (% of span)',.25,0)],'Error % span = 100 × (measured − expected) / (URV − LRV)','50.2 measured against 50 expected on a 0–100 range is +0.2% of span, within an entered ±0.25% tolerance.','calibration-error-and-tolerance'),
}
for slug in ['loop-checklist','fat-sat-checklist','cause-effect-checklist']:
 configs[slug]=([text('tag','Instrument tag / test record ID','DEMO-001'),text('reference','Approved drawing / procedure / cause → effect reference'),text('witness','Witness / reviewer'),text('notes','Results, timing, deviations and notes')],'Reviewed = Pass + Fail + Not applicable; acceptance requires review','Use a unique record ID for each instrument, system or cause/effect pair. Changing the ID loads that record from this browser.','commissioning-records' if slug!='cause-effect-checklist' else 'voting-and-cause-effect')
SOURCES={
 'rtd-pt100':('Pt100 reference coefficients','https://www.sensingtemp.com/resources-rtd-resistance-tables.html'),
 'thermocouple-converter':('NIST Monograph 175','https://www.nist.gov/publications/temperature-electromotive-force-reference-functions-and-tables-letter-designated'),
 'valve-cv':('Emerson liquid control valve sizing','https://www.emerson.com/en/final-control/catalog/products-and-software/valves/control-valves/control-valves-sizing'),
 'hydrostatic-level':('Emerson differential pressure principles','https://www.emerson.com/en/measurement-instrumentation/catalog/pressure-measurement/differential-pressure'),
 'wet-leg-dry-leg':('Emerson DP level measurement','https://www.emerson.com/en/measurement-instrumentation/catalog/pressure-measurement/pressure-transmitters/differential-pressure-level-transmitter')}
def control(f):
 k=f['key'];label=f'<label id="{k}-label" for="{k}">{E(f["label"])}</label>'
 if f['type']=='select':c=f'<select id="{k}">'+''.join(f'<option value="{E(str(v))}">{E(t)}</option>' for v,t in f['options'])+'</select>'
 else:
  attrs=' '.join(f'{key}="{E(str(f[key]))}"' for key in ['type','value','min','max','step'] if f.get(key) is not None)
  c=f'<input id="{k}" {attrs}'+(' inputmode="decimal"' if f['type']=='number' else '')+'>'
  if f['type']=='range':c+=f'<output for="{k}" data-range-output="{k}">{f["value"]}</output>'
 return '<div class="field">'+label+c+'</div>'
def build():
 rows=json.loads((R/'assets/data/tools.json').read_text());header=(R/'templates/header.html').read_text();footer=(R/'templates/footer.html').read_text()
 for tool in rows:
  slug=tool['slug']
  if slug not in configs:continue
  fields,formula,example,article=configs[slug];tool['status']='available';tool['visual']='Live visual';tool.pop('inputs',None);tool.pop('outputs',None)
  ref=SOURCES.get(slug);reference=f'<p><a href="{ref[1]}" target="_blank" rel="noopener">{E(ref[0])} ↗</a></p>' if ref else ''
  checklist='<div id="checklist-area"></div><p id="save-state" role="status">Progress is stored only in this browser.</p>' if 'checklist' in slug else ''
  html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{E(tool['description'])} Free interactive tool with live visual feedback."><meta name="theme-color" content="#f5f8fc"><title>{E(tool['title'])} | Instrumentation Hub</title><link rel="stylesheet" href="../assets/css/hub.css?v=20260923"><link rel="stylesheet" href="../assets/css/engineering.css?v=1"></head><body>{header}<main id="main-content"><section class="page-hero compact-hero"><div class="container"><div class="breadcrumbs"><a href="../#tools">All tools</a> / {E(tool['title'])}</div><div class="eyebrow">Free engineering workspace · Live visual</div><h1>{E(tool['title'])}</h1><p class="hero-copy">{E(tool['description'])} Change an input to see the result and diagram update.</p></div></section><div class="container engineering-app" id="engineering-app" data-tool="{slug}"><div class="engineering-grid"><section class="tool-surface"><h2>Inputs</h2><form id="tool-inputs" onsubmit="return false"><div class="field-grid">{''.join(control(f) for f in fields)}</div>{checklist}</form><div class="inline-actions"><button class="button small ghost" type="button" id="reset-tool">Reset</button><button class="button small" type="button" id="export-report">Export CSV report</button></div></section><section class="visual-surface"><div class="visual-heading"><h2>See the change</h2><span class="status">Live</span></div><div id="live-visual"></div><div id="live-results" class="result-grid" aria-live="polite"></div><p id="tool-message" class="tool-message" role="status"></p></section></div><div id="extra-results"></div><section class="tool-explanation"><div><h2>How it works</h2><p class="formula">{E(formula)}</p><h3>Try this example</h3><p>{E(example)}</p></div><div><h2>Understand the result</h2><p>Check the model assumptions shown below the result. Match units, instrument configuration and acceptance criteria to your project.</p><a class="button ghost" href="../blog/{article}.html">Read the practical guide →</a>{reference}</div></section></div></main>{footer}<script src="../assets/js/hub.js?v=20260923"></script><script src="../assets/js/engineering-math.js?v=1"></script><script src="../assets/js/engineering-tools.js?v=1"></script></body></html>'''
  (R/'tools'/f'{slug}.html').write_text(html)
 (R/'assets/data/tools.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
if __name__=='__main__':build()
